services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-diana-mentor
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: mentor-diana-postgres
    ports:
      - "5432:5432"
    env_file:
    - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
