CREATE SCHEMA "DIANA_MENTOR";

CREATE SEQUENCE DIANA_MENTOR.UTILISATEUR_Seq;
CREATE SEQUENCE DIANA_MENTOR.REGION_Seq;
CREATE SEQUENCE DIANA_MENTOR.DISTRICT_Seq;
CREATE SEQUENCE DIANA_MENTOR.COMMUNE_Seq;
CREATE SEQUENCE DIANA_MENTOR.FOKONTANY_Seq;

CREATE TABLE DIANA_MENTOR.UTILISATEUR (
   UTILISATEUR_ID               INT8                 not null,
   UTILISATEUR_NOM              VARCHAR(250)         null,
   UTILISATEUR_PRENOM           VARCHAR(250)         null,
   UTILISATEUR_PASSWORD           VARCHAR(100)         null,
   UTILISATEUR_INUTILISABLE_FLAG BOOL                 null,
   UTILISATEUR_EMAIL             VARCHAR(250)         not null,
   constraint PK_UTILISATEUR primary key (UTILISATEUR_ID)
);

-- L'adresse email doit être unique et obligatoire
create unique index UTILISATEUR_EMAIL_INDEX on DIANA_MENTOR.UTILISATEUR (UTILISATEUR_EMAIL );

